apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "java-application.fullname" . }}
  labels:
    {{- include "java-application.labels" . | nindent 4 }}
data:
  java-app-sf-endpoint: {{ .Values.java.sfEndpoint | quote }}
