apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "java-application.fullname" . }}
  labels:
    {{- include "java-application.labels" . | nindent 4 }}
data:
  java-app-sf-endpoint: {{ .Values.java.sfEndpoint | quote }}
  java-app-profile: {{ .Values.java.appProfile | quote }}
  java-app-kafka-broker: {{ .Values.java.kafkaBroker | quote }}
  java-app-schema-registry-url: {{ .Values.java.schemaRegistryUrl | quote }}
  java-app-trust-store: {{ .Values.java.trustStore | quote }}
  java-app-additional-arguments: {{ .Values.java.additionalArguments | quote }}
  monitoring-metrics-topic: {{ .Values.monitoring.metricsKafkaTopic | quote }}
  monitoring-alert-from: {{ .Values.monitoring.alert.from | quote }}
  monitoring-alert-to: {{ .Values.monitoring.alert.to | quote }}
  monitoring-alert-service-name: {{ .Values.monitoring.alert.serviceName | quote }}