apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "java-application.fullname" . }}
  labels:
    {{- include "java-application.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "java-application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "java-application.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "java-application.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: SF_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "java-application.fullname" . }}
                  key: java-app-sf-user-secret
            - name: SF_PSSWD
              valueFrom:
                secretKeyRef:
                  name: {{ include "java-application.fullname" . }}
                  key: java-app-sf-password-secret
            - name: SF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "java-application.fullname" . }}
                  key: java-app-sf-token-secret
            - name: SF_SERVER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "java-application.fullname" . }}
                  key: java-app-sf-endpoint
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.java.image.repository }}:{{ .Values.java.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.java.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9080
              protocol: TCP
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "/bin/ps -ef | grep java | grep -v grep"]
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "/bin/ps -ef | grep java | grep -v grep"]
            initialDelaySeconds: 30
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
