apiVersion: v1
kind: Secret
metadata:
  name: {{ include "java-application.fullname" . }}
  labels:
    {{- include "java-application.labels" . | nindent 4 }}
type: Opaque
data:
  java-app-sf-user-secret: {{ .Values.java.sfUser | b64enc | quote }}
  java-app-sf-password-secret: {{ .Values.java.sfPassword | b64enc | quote }}
  java-app-sf-token-secret: {{ .Values.java.sfToken | b64enc | quote }}
