apiVersion: v1
kind: Secret
metadata:
  name: {{ include "java-application.fullname" . }}
  labels:
    {{- include "java-application.labels" . | nindent 4 }}
type: Opaque
data:
  java-app-sf-user-secret: {{ .Values.java.sfUser | b64enc | quote }}
  java-app-sf-password-secret: {{ .Values.java.sfPassword | b64enc | quote }}
  java-app-sf-token-secret: {{ .Values.java.sfToken | b64enc | quote }}
  java-app-secret-kafka-production-api-key: {{ .Values.java.kafkaProductionApiKey | b64enc | quote }}
  java-app-secret-kafka-production-api-secret: {{ .Values.java.kafkaProductionApiSecret | b64enc | quote }}
  java-app-secret-schema-registry-production-auth-key: {{ .Values.java.schemaRegistryProductionAuthKey | b64enc | quote }}
  java-app-secret-schema-registry-production-auth-secret: {{ .Values.java.schemaRegistryProductionAuthSecret | b64enc | quote }}